id: PA75A415F
initial_creation_type: input
source_metadata:
  title: Yangthang Rinpoche Series
  language: en
  description: Texts by Domang Yangthang Rinpoche (mdo mang g.yang thang rin po che,
    1929–2016), the renowned incarnation of Domang Dorje Dechen Lingpa (1857–1928).
  volume:
    ee5d3dc588ab4fe2925fcb7b98d8fab2:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    2c9e5df7ea6b4b4ba672a8deae7145d3:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers
created_at: '2022-03-01T02:01:26.941491'
last_modified_at: '2022-03-01T02:01:26.941497'
